[package]
name = "esp-idf-sys"
version = "0.1.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["xtensa", "hal", "esp", "esp32", "esp8266", "idf"]
description = "Implementation of the embedded-svc traits for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/ivmarkov/esp-idf-sys"
license = "MIT"

[dependencies]
anyhow = "*"
scopeguard = "1.1.0"
lazy_static = "1.4.0"
embedded-svc = {path = "../embedded-svc"}
esp-idf-sys = {path = "../esp-idf-sys", features = ["esp32", "std"]}
