[package]
name = "esp-idf-svc"
version = "0.19.4"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["embedded", "svc", "idf", "esp-idf", "esp32"]
description = "Implementation of the embedded-svc traits for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/ivmarkov/esp-idf-svc"
license = "MIT OR Apache-2.0"
readme = "README.md"

[features]
default = ["std"]

std = ["alloc", "anyhow/std", "esp-idf-sys/std", "embedded-svc/std"]
alloc = ["cstr_core/alloc", "anyhow"]

binstart = []
libstart = []

[dependencies]
enumset = "1"
log = "0.4"
cstr_core = "0.2"
anyhow = { version = "1.0", features = ["backtrace"], optional = true }
mutex-trait = "0.2"
embedded-svc = "0.8.4"
esp-idf-sys = "0.19"

[build-dependencies]
embuild = "0.23"
anyhow = "1"
