[package]
name = "esp-idf-svc"
version = "0.14.0"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["xtensa", "hal", "esp", "esp32", "esp8266", "idf"]
description = "Implementation of the embedded-svc traits for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/ivmarkov/esp-idf-sys"
license = "MIT"

[features]
default = ["std"]

std = ["alloc", "anyhow/std"]
alloc = ["cstr_core/alloc", "anyhow"]

binstart = []
libstart = []

[dependencies]
enumset = "1"
log = "0.4"
cstr_core = "0.2"
anyhow = {version = "1.0", features = ["backtrace"], optional = true}
mutex-trait = "0.2"
embedded-svc = {version = "0.7", git = "https://github.com/ivmarkov/embedded-svc.git"}
#embedded-svc = {version = "*", path = "../embedded-svc"}
esp-idf-sys = {version = "0.14", git = "https://github.com/ivmarkov/esp-idf-sys.git"}
#esp-idf-sys = {version = "*", path = "../esp-idf-sys"}
