[package]
name = "esp-idf-svc"
version = "0.4.1"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support"]
keywords = ["xtensa", "hal", "esp", "esp32", "esp8266", "idf"]
description = "Implementation of the embedded-svc traits for ESP-IDF (Espressif's IoT Development Framework)"
repository = "https://github.com/ivmarkov/esp-idf-sys"
license = "MIT"

[features]
default = ["binstart"]

binstart = []
libstart = []

[dependencies]
anyhow = {version = "1.0", features = ["backtrace"]}
log = "0.4"
scopeguard = "1.1"
lazy_static = "1.4"
libc = "0.2"
embedded-svc = {version = "0.4", git = "https://github.com/ivmarkov/embedded-svc.git"}
#embedded-svc = {version = "*", path = "../embedded-svc"}
esp-idf-sys = {version = "0.4", git = "https://github.com/ivmarkov/esp-idf-sys.git"}
#esp-idf-sys = {version = "*", path = "../esp-idf-sys"}
